### ISSUE TITLE
SHOWHIDDEN error

### ISSUE THREAD

**Issue by Barbaross93** [huijunchen9260/tabbed-hjc#1]
Hey, I'm migrating from reddit to report the output of the commands that you asked me to do. The first one's (i.e. `cwin="$(xwininfo -children -id $1 | grep '^ 0x' | sed -e 's@^ *\(0x[0-9a-f]*\) "\([^"]*\)".*@\1 \2@')" echo $cwin ' output was: `xwininfo: error: -id requires argument`
The other command outputted nothing.

**Comment by huijunchen9260** [comment]
My bad. the code should be

```
cwin="$(xwininfo -children -id $XEMBED | grep '^     0x' | sed -e 's@^ *\(0x[0-9a-f]*\) "\([^"]*\)".*@\1 \2@')" 
echo $cwin
```

and 

```
IFS=':' &&
for win in $(printf '%s' "$cwin" | tr '\n' ':'); do unset IFS &&
cwid=$(printf '%s' "$win" | cut -d ' ' -f 1) &&
xwininfo -id $cwid -stats |
grep -q 'IsUnMapped' &&
printf '%s\n' "$win"; done
```

and also try to pipe the above output to dmenu / rofi to see whether the prompt opened

**Comment by Barbaross93** [comment]
Hmmm, I'm still getting `xwininfo: error: -id requires argument` after the first command. The second block after piping into `rofi -dmenu -i -l 5` worked fine, however, I can see the out put `for win in $(printf '%s' "$cwin" | tr '\n' '` followed by the string that was typed into rofi. So if I typed "spaghett" in the rofi prompt I get: `for win in $(printf '%s' "$cwin" | tr '\n' 'spaghett`

**Comment by huijunchen9260** [comment]
You should open a terminal embedded into tab, and the first code will work. If still not work, then

```
cwin="$(xwininfo -children -id $(xdotool getactivewindow) | grep '^     0x' | sed -e 's@^ *\(0x[0-9a-f]*\) "\([^"]*\)".*@\1 \2@')" 
echo $cwin
```

Let's say you have three tabs open and hide two tabs.

`xwininfo -children -id $XEMBED` is to get a list of the child windows in tabbed, which id is represented by `$XEMBED`. The rest of the code is just manipulating the standard output so that only child windows' windows id and windows name appears. We store the output to `cwin` variable in the form `winid winname` (e.g. `0x520000a urxvt`)

After you run the first command, your terminal should have a `cwin` variable. We use the following `for` loop to find which one is hidden. 

Note that by default shell script has the IFS (internal field separator) set as space, tab and newline three characters, If we just use `cwin` into `for` loop, we will have six rather than three input for `for` loop since shell treat both `winid` and `winname` as different field.

To overcome the above difficulty, I set IFS as `:` to avoid such problem. Thus, when we put `cwin` into `for` loop, we also need to transform (`tr`) the newline character (`\n`) into colon (`:`) so that the `for` loop precisely based on colon. That is to say, the output of `printf '%s' "$cwin" | tr '\n' ':'` should be

```
0x2e0000a urxvt:0x3e0000a urxvt:0x520000a urxvt
```

, and each `for` loop will only accept a pair of `winid winname`.

After that, we `unset IFS` to default state to prevent any possible error.

We isolate only the windows id, pipe that windows id into `xwininfo` to retrieve the status of hidden. If hidden, we output the hidden pair of `winid winname` into standard output. Then pipe to `rofi` or `dmenu` to show a prompt for user to choose which hidden window to show.

Hope my explanation will help you understand what is happening in the `SHOWHIDDEN` function. If above code works for you, to further debug, you can try to remap the `SHOWHIDDEN` function into other keybinding that does not comflict to any other keybind existing in your system, and tell me the result.

**Comment by Barbaross93** [comment]
I think I've figured out the problem. The command did indeed work, but only if I made a new terminal using one of the commands you have to add a terminal to tabbed (and then executing that code in the new terminal). I'm using a bspwm specific script to achieve tabbing and what I was doing was taking your functions and putting them into my version of tabbed. Clearly there was a discrepancy there in the way you handled adding windows to tabbed versus the way my script does it. I'll go ahead and mark this closed since this is technically not a problem on your end

**Comment by huijunchen9260** [comment]
Btw, in your screencast, https://imgur.com/a/N0661Hg, how do you let your PS1 appear on the tab?

**Comment by Barbaross93** [comment]
Sorry, I'm not sure what the PS1 is? Is it the "barbarossa@Eternity: ~" bit?
 In either case, it's probably the result of the scripts I'm using. Here's
the main one called bsptab: https://pastebin.com/D0uDN1wa and it relies on
another one called tabc: https://pastebin.com/U9M7eizc

**Comment by huijunchen9260** [comment]
Yeah, that is exactly what I am asking. Could you please explain the code a bit so that it is easier for me to understand the code?

**Comment by Barbaross93** [comment]
Unfortunately I can't explain it to you, because shamefully I didn't write
it. https://github.com/jpentland This is the user I got it from. Hopefully
he can explain what he did exactly
